# Generated by Django 4.2.4 on 2023-08-30 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='reciperequirements',
            old_name='quantity_required',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'tablespoon'), ('lbs', 'pounds')], default='tbsp', max_length=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
