# Generated by Django 4.2.4 on 2023-08-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='timestamp',
            new_name='purchase_date',
        ),
    ]
