# Generated by Django 4.2.4 on 2023-08-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_timestamp_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'tablespoon'), ('lbs', 'pounds'), ('g', 'grams'), ('ou', 'ounces')], default='tbsp', max_length=5),
        ),
    ]
