# Generated by Django 4.2.4 on 2023-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'tablespoon'), ('lbs', 'pounds'), ('g', 'grams'), ('ou', 'ounces'), ('eggs', 'eggs')], default='tbsp', max_length=5),
        ),
    ]
